version: "3.9"
services:
  pocketbase:
    build:
      context: ./
      dockerfile: ./build/package/pocketbase/Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data

  # ui:
  #   build: ./ui/
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - ENV_API_URL=http://template.natron.io:8090


volumes:
  pb_data: {}
